name: Deploy

on:
  push:
      branches:
        - master

jobs:
  on-merge:
    runs-on: ubuntu-latest
    name: On_merge
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Reading PR description
        run: echo ${{ github.event.pull_request.title }}
