name: Deploy

on:
  push:
    branches:
      - directory_test

jobs:
  make_directory:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Make directory using python
      run: python3 make_dir.py
    
    - name: Check tmp
      run: ls /tmp

    - name: Check PRs
      run: ls /tmp/prs