name: flake8 Lint

on:
  push:
    branches:
      - master

build:
  on-merge:
    runs-on: ubuntu-latest
    name: On_merge
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: "print completed"
        run: echo "Merge completed"