name: flake8 Lint

on:
  push:
    branches:
      - master

jobs:
  on-merge:
    runs-on: ubuntu-latest
    name: On_merge
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - uses: 8BitJonny/gh-get-current-pr@2.1.3
        id: PR
      - run: echo "Your PR number is ${{ steps.PR.outputs.number }} and its JSON is ${{ steps.PR.outputs.pr }}"
      - name: "print completed"
        run: echo "Merge completed"