name: flake8 Lint

on:
  push:
    branches:
      - master

jobs:
  on-merge:
    runs-on: ubuntu-latest
    name: On_merge
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2

      - name: Reading PR description
        run: echo "${{ github.event.pull_request.title }} PR- ${{ github.event.pull_request.description }}"
