name: flake8 Lint

on:
  push:
    branches:
      - master

jobs:
  on-merge:
    runs-on: ubuntu-latest
    name: On_merge
    steps:
      - name: Check out source repository
        uses: actions/checkout@master
        with:
          description: |
            PR no. ${{ github.event.pull_request.number }}
            PR title ${{ github.event.pull_request.title }}

      - name: Reading PR description
        run: echo "${{ github.event.pull_request.title }} PR- ${{ github.event.pull_request.description }}"
