name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
   types: [closed]

jobs:
  print_title_of_pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
    - name: Print PR number
      run: echo ${{ github.event.pull_request.number }} 

    - name : Print Title of PR
      run: echo The Title of your PR is ${{ github.event.pull_request.title }}
    
    - name: Print text of PR
      run: echo Text is ${{ github.event.pull_request.body }}

    - name: Print author name
      run: echo author name ${{ github.event.pull_request.issue.user.login }}

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
