name: Deploy

on:
  push:
  pull_request:
   types: [closed]
   branches: [master]

jobs:
  print_title_of_pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
    - name : Print Title of PR
      run: echo The Title of your PR is ${{ github.event.pull_request.title }}
    
    - name: Print text of PR
      run: echo Text is ${{ github.event.pull_request.description }}

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"