on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: manishpjt/lintly-flake8-github-action@v1.1
        with:
          # The GitHub API token to create reviews with
          token: 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
          # Fail if "new" violations detected or "any", default "new"
          failIf: new
          # Additional arguments to pass to flake8, default "." (current directory)
          args: "--ignore=E121,E123 ."